from __future__ import annotations
import argparse
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
SIMULATOR_DIR = PROJECT_ROOT / 'simulator'
CONFIG_DIR = PROJECT_ROOT / 'config' / 'booksim_configs'
DATA_RAW = PROJECT_ROOT / 'data' / 'raw'
DATA_PROCESSED = PROJECT_ROOT / 'data' / 'processed'
CONFIG_TEMPLATE = '// AUTO-GENERATED by sweep_configs.py. Do not edit.\n// run_id = {run_id}\n\ntopology = mesh;\nk        = {k};\nn        = {n};\n\nrouting_function = dor;\npacket_size      = 1;\n\nnum_vcs     = {num_vcs};\nvc_buf_size = {vc_buf_size};\nwait_for_tail_credit = 1;\n\nvc_allocator = islip;\nsw_allocator = islip;\nalloc_iters  = 2;\n\ncredit_delay   = 2;\nrouting_delay  = 0;\nvc_alloc_delay = 1;\nsw_alloc_delay = 1;\nst_final_delay = 1;\n\ninput_speedup    = 1;\noutput_speedup   = 1;\ninternal_speedup = 1.0;\n\nsim_type       = throughput;\ntraffic        = {traffic};\ninjection_rate = {injection_rate};\nuse_read_write = 0;\n\nwarmup_periods = 2;\nsample_period  = {sample_period};\nsim_count      = {sim_count};\n\n// flow tracking output\ninjected_flits_out      = smoke_injected.csv;\nejected_flits_out       = smoke_ejected.csv;\nreceived_flits_out      = smoke_received.csv;\nsent_flits_out          = smoke_sent.csv;\nstored_flits_out        = smoke_stored.csv;\noutstanding_credits_out = smoke_credits.csv;\n'

@dataclass(frozen=True)
class SweepCell:
    traffic: str
    injection_rate: float

    @property
    def run_id(self) -> str:
        rate_int = int(round(self.injection_rate * 100))
        return f'{self.traffic}_ir{rate_int:03d}'

def _build_config(*, cell: SweepCell, k: int, n: int, num_vcs: int, vc_buf_size: int, sample_period: int, sim_count: int, mesh_label: str) -> str:
    full_run_id = f'{mesh_label}_{cell.run_id}'
    return CONFIG_TEMPLATE.format(run_id=full_run_id, k=k, n=n, num_vcs=num_vcs, vc_buf_size=vc_buf_size, traffic=cell.traffic, injection_rate=cell.injection_rate, sample_period=sample_period, sim_count=sim_count)

def run_one(*, cell: SweepCell, cfg_path: Path, raw_out: Path, processed_out: Path, booksim: Path, k: int, n: int, num_vcs: int, vc_buf_size: int, skip_existing: bool) -> bool:
    processed_csv = processed_out / 'router_timeseries.csv'
    if skip_existing and processed_csv.is_file():
        print(f'[sweep] {cell.run_id}: đã có {processed_csv.name}, skip.')
        return True
    if raw_out.exists():
        shutil.rmtree(raw_out)
    raw_out.mkdir(parents=True, exist_ok=True)
    cfg_local = raw_out / 'config.cfg'
    cfg_local.write_text(cfg_path.read_text())
    print(f'[sweep] {cell.run_id}: BookSim2 ...', end=' ', flush=True)
    proc = subprocess.run([str(booksim), str(cfg_local)], cwd=raw_out, capture_output=True, text=True, check=False)
    (raw_out / 'booksim_run.log').write_text(proc.stdout + '\n--- STDERR ---\n' + proc.stderr)
    required = ['smoke_injected.csv', 'smoke_ejected.csv', 'smoke_stored.csv', 'smoke_received.csv', 'smoke_sent.csv']
    missing = [f for f in required if not (raw_out / f).is_file()]
    if missing:
        print(f'FAIL - thiếu {missing}, rc={proc.returncode}')
        return False
    print('OK', end=' ', flush=True)
    print(', parse ...', end=' ', flush=True)
    parse = subprocess.run([sys.executable, str(SIMULATOR_DIR / 'parse_logs.py'), '--raw-dir', str(raw_out), '--out-dir', str(processed_out), '--k', str(k), '--n', str(n), '--num-vcs', str(num_vcs), '--vc-buf-size', str(vc_buf_size)], capture_output=True, text=True, check=False)
    if parse.returncode != 0:
        print(f'FAIL parse - {parse.stderr.strip()}')
        return False
    print('OK')
    return True

def main(argv: list[str] | None=None) -> int:
    p = argparse.ArgumentParser(description='Sweep BookSim2 configs')
    p.add_argument('--k', type=int, default=4)
    p.add_argument('--n', type=int, default=2)
    p.add_argument('--num-vcs', type=int, default=4)
    p.add_argument('--vc-buf-size', type=int, default=8)
    p.add_argument('--sample-period', type=int, default=100)
    p.add_argument('--sim-count', type=int, default=20)
    p.add_argument('--traffic', nargs='+', default=['uniform', 'transpose', 'neighbor', 'hotspot'])
    p.add_argument('--injection-rate', nargs='+', type=float, default=[0.1, 0.2, 0.3, 0.4])
    p.add_argument('--skip-existing', action='store_true')
    p.add_argument('--booksim', type=Path, default=SIMULATOR_DIR / 'booksim2' / 'src' / 'booksim')
    args = p.parse_args(argv)
    mesh_label = f'mesh_{args.k}x{args.k}'
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    cells = [SweepCell(t, ir) for t in args.traffic for ir in args.injection_rate]
    print(f'[sweep] tổng {len(cells)} cell: {len(args.traffic)} traffic × {len(args.injection_rate)} rate')
    ok = 0
    fail: list[str] = []
    for cell in cells:
        full_run_id = f'{mesh_label}_{cell.run_id}'
        cfg_path = CONFIG_DIR / f'{full_run_id}.cfg'
        cfg_path.write_text(_build_config(cell=cell, k=args.k, n=args.n, num_vcs=args.num_vcs, vc_buf_size=args.vc_buf_size, sample_period=args.sample_period, sim_count=args.sim_count, mesh_label=mesh_label))
        raw_out = DATA_RAW / full_run_id
        processed_out = DATA_PROCESSED / full_run_id
        if run_one(cell=cell, cfg_path=cfg_path, raw_out=raw_out, processed_out=processed_out, booksim=args.booksim, k=args.k, n=args.n, num_vcs=args.num_vcs, vc_buf_size=args.vc_buf_size, skip_existing=args.skip_existing):
            ok += 1
        else:
            fail.append(full_run_id)
    print(f'\n[sweep] tóm tắt: OK {ok}/{len(cells)}')
    if fail:
        print(f'[sweep] FAIL: {fail}')
        return 1
    return 0
if __name__ == '__main__':
    raise SystemExit(main())
